bag/src/bagobject.py
Bij mij werkte de import van mutaties niet goed. Wat er gebeurde bij bijwerken bestaande BAG objecten:
* Nieuwe versie van BAG-object werd toegevoegd (met uiteraard einddatum = NULL)
* Bestaande versie van BAG-object werd gewijzigd met een nieuwe einddatum. 
Dat laatste ging niet goed, omdat de update query zocht naar BAG-record met einddatum = NULL (namelijk de oude versie van een BAG-object) en daarmee werden twee BAG-records bijgewerkt:
* De net nieuwe toegevoegde
* De oorspronkelijke
Ik heb dit gewijzigd: de update query kijkt nu naar begindatum ipv einddatum. BAG identificatie, begindatum (en aanduiding record actief  en aanduidingrecordcorrectie) vormen een unieke key.
Mocht er behoefte zijn aan een eenvoudige testcase, laat maar weten.
=> Wijziging SQL UPDATE query voor mutaties

bag/bin/bag-extract.sh, bag/src/bagextract.py
Ik heb twee kleine fixes uitgevoerd. Allereerst een print commando python3 compatibel gemaakt. Toen ik daarna nog meer problemen tegen kwam tijdens het uitvoeren van runtest.sh heb ik bag-extract.sh aangepast zodat wordt gecontroleerd welke python versie je draait en op basis daarvan de juiste python executable wordt gebruikt.
=> Twee kleine fixes i.v.m. python 3 als standaard op mijn systeem

bag/db/data/cbs-gemeentenperprovincie-2015.csv
Was 'De Friese Meren' (1921) tot 2015-07-01.
N.a.v. de [BAG Friese Meren?](https://groups.google.com/d/msg/nlextract/jlDKCYdL6ZU/jakfwcSJBwAJ) discussie op de mailinglist.
=> Update gemeentecode & naam voor 'De Fryske Marren' (1940).

bag/db/script/bag-db.sql, bag/db/script/bag-view-actueel-bestaand.sql, bag/src/bagattribuut.py, bag/src/bagobject.py
Deze views zijn ook toegevoegd. Op deze manier zouden er bij het joinen van de relatietabellen met andere tabellen (bijv. pand) minder dubbelingen op moeten treden. Zie issue #146 voor meer informatie. Dit pull request is een alternatief voor pull request #148.
Om de *actueelbestaand-views te genereren, zijn er twee werkwijzen mogelijk. De eerste manier is het joinen van de views met verblijfsobject en de tweede manier is het toevoegen van meer informatie over de verblijfsobjecten, nl. status en geom_valid, zodat de actueelbestaand-views op dezelfde manier als bij verblijfsobjecten gemaakt kunnen worden. Bij het maken van de views d.m.v. het joinen met verblijfsobjecten was de verwachting dat dit zwaar ten koste zou gaan van de performance. Dit bleek ook zo het geval te zijn. Dus het …
=> BAG relatietabellen geschikt gemaakt voor *actueelbestaand-views

bag/db/script/adres-tabel.sql, bag/db/script/bag-db.sql, bag/db/script/bag-view-actueel-bestaand.sql, bag/db/script/gemeente-provincie-tabel.sql
Geconstateerd door Matthijs Laan, a.d.h.v. recente dumps.
Zijn bericht is op 16-08 jl. naar de mailinglijst verstuurd.
> Sinds de dump van juli van http://data.nlextract.nl/bag/postgis/bag-laatst.backup staat er in de views een cast van de geo kolom, bijvoorbeeld:
> 
> CREATE OR REPLACE VIEW bag20160812.pandactueel AS 
>  SELECT pand.gid,
> ...
>     pand.geovlak::geometry(PolygonZ,28992) AS geovlak
> 
> Dit zorgt ervoor dat een query als onderstaand op de view niet de index gebruikt maar een sequentiele scan:
> 
> explain SELECT count("geovlak") FROM "bag20160812"."pandactueel" WHERE  "geovlak" && ST_GeomFromText('POLYGON ((148547.96 415797.87999999995, 148547.96 415907.08, 148657.16 415907.08, 148657.16 415797.87999999995, 148547.96 415797.87999999995))', 28992);
>  Aggregate …
=> Queries op geoviews maken geen gebruik meer van de spatial index

bag/db/data/gemeentelijke-indeling.xml, bag/src/gemeentelijke-indeling.py
Per 1 januari 2017 word de nieuwe gemeentelijke indeling actief:
* Schijndel (0844), Sint-Oedenrode (0846) & Veghel (0860) komen te vervallen,
en worden de nieuwe gemeente Meierijstad (1948).
Zie ook:
* [CBS - Gemeentelijke indeling op 1 januari 2017](https://www.cbs.nl/nl-nl/onze-diensten/methoden/classificaties/overig/gemeentelijke-indelingen-per-jaar/indeling%20per%20jaar/gemeentelijke-indeling-op-1-januari-2017)
* [Wikipedia - Gemeentelijke herindeling in Nederland](https://nl.wikipedia.org/wiki/Gemeentelijke_herindeling_in_Nederland#2017)
Helaas gebruikt CBS voor de XLS weer een andere kolomindeling, waarvoor support is toegevoegd in `parse_cbs_data()`.
=> Update gemeente-provincie koppeling voor 2017

bag/db/data/gemeentelijke-indeling.xml
Per 1 januari 2018 word de nieuwe gemeentelijke indeling actief:
* Bellingwedde (0007) & Vlagtwedde (0048) komen te vervallen, en worden de nieuwe gemeente Westerwolde (1950).
* Hoogezand-Sappenmeer (0018), Slochteren (0040) & Menterwolde (1987) komen te vervallen, en worden de nieuwe gemeente Midden-Groningen (1952).
* het Bildt (0063), Franekeradeel (0070), Menameradiel (1908) en een deel van Littenseradiel (0140) komen te vervallen, en worden de nieuwe gemeente Waadhoeke (1949).
* Leeuwarderadeel (0081) en een deel van Littenseradiel (0140) komen te vervallen, en worden bij de gemeente Leeuwarden (0080) gevoegd.
* Een deel van Littenseradiel (0140) wordt bij gemeente Súdwest-Fryslân (1900) gevoegd.
* Rijnwaarden (0196) komt te vervallen, en wordt in de gemeente Zevenaar (0299) …
=> Update gemeente-provincie koppeling voor 2018.

bgt/etl/data/bronhouders.csv
update van de bronhouderslijst per 1 januari 2018 op basis van https://www.kadaster.nl/bgt-documentatie
=> update bronhouders per 2018-01-01

bgt/etl/download-bgt.sh, bgt/etl/sql/create-final-tables-v2.1.1.sql
Deeloplossing voor #233 (allen BGT).
De datum/tijdvelden worden nog steeds in de temp-tabellen ingeladen. Bij het overzetten naar de 'echte' tabellen wordt de tijdzone geïntroduceerd. Hierbij is aangenomen dat alles in 'Europe/Amsterdam' is.
=> Bgt timezone

bag/db/script/bag-view-actueel-bestaand.sql
BAG: De 'actueel' en 'actueelbestaand' views maken nog gebruik van ``localtime`` wat fouten kan veroorzaken als de server in een andere tijdzone staat - zie discussie in issue #223 .
In issue #238 is een flinke discussie gevoerd over wel/geen tijdzones te gebruiken. Uiteindeljk is besloten om de Europe/Amsterdam tijdzone aan te houden.
=> Set 'actueel' views use now() instead of localtime

bag/db/data/gemeentelijke-indeling.xml
Per 1 januari 2019 word de nieuwe gemeentelijke indeling actief:
* Bedum (0005), Eemsmond (1651), De Marne (0053) & een deel van
Winsum (0053) komen te vervallen, en worden de nieuwe gemeente
Het Hogeland (1966).
* Ten Boer (0009) & Haren (0017) komen te vervallen, en worden bij
de gemeente Groningen (0014) gevoegd.
* Grootegast (0015), Leek (0022), Marum (0025), Zuidhorn (0056) &
een deel van Winsum (0005) komen te vervallen, en worden de nieuwe
gemeente Westerkwartier (1969).
* Dongeradeel (0058), Kollumerland en Nieuwkruisland (0079) &
Ferwerderadiel (1722) komen te vervallen, en worden de nieuwe
gemeente Noardeast-Fryslân (1970).
* Geldermalsen (0236), Neerijnen (0304) & Lingewaal (0733) komen
te vervallen, en worden de nieuwe gemeente West Betuwe (1960).
* Haarlemmerliede en …
=> Update gemeente-provincie koppeling voor 2019.

VERSIES, bag/README, doc/source/bagextract.rst, doc/source/bgtextract.rst, doc/source/brkextract.rst, doc/source/top10extract.rst
Vervangt alle verwijzingen in de master branch van `http://www.nlextract.nl/file-cabinet` naar werkende, relevante links
=> Vervang referenties aan http://www.nlextract/file-cabinet (link rot)

bag/bin/bag-extract.sh, bag/bin/gemeentelijke-indeling.sh, bag/src/bagattribuut.py, bag/src/bagconfig.py, bag/src/bagdownloadgui.py, bag/src/bagextract.py, bag/src/bagfilereader.py, bag/src/bagobject.py, bag/src/bestuurlijkobject.py, bag/src/configeditorgui.py, bag/src/gemeentelijke-indeling.py, bag/src/geocode/GeoCode-pc-hn-ext.py, bag/src/geocode/GeoCode-pc-hn-hl-tv.py, bag/src/log.py, bag/src/oracledb.py, bag/src/postgresdb.py, bag/src/processor.py
Python 2 is EOL since 2020-01-01, high time to switch to Python 3.
The port is quite straight forward.
XML needs to be read as bytes, because parsing strings with an XML declaration is not supported.
This requires later decoding to create a geometry from the GML.
The `gemeentelijke-indeling.py` script uses [xlrd](https://pypi.org/project/xlrd/) instead of [pyExcelerator](https://pypi.org/project/pyExcelerator/) for Python 3 support.
The remaining changes are mostly `print` & `Exception` syntax, only using `io.StringIO` & `io.BytesIO`, and not settings the default encoding.
=> Switch to Python 3

bag/src/processor.py
With the switch to Python3 `etree.tostring()` returns bytes.
Before inserting the content of `Leveringsdocument-BAG-Extract.xml` it should be decoded to a string to not store bytes in the database.
=> Decode Levering XML to string.

bag/db/data/gemeentelijke-indeling.xml, bag/src/gemeentelijke-indeling.py
Per 1 januari 2021 word de nieuwe gemeentelijke indeling actief:
* Appingedam (0003), Delfzijl (0010), en Loppersum (0024) komen te vervallen,
en worden de nieuwe gemeente Eemsdelta (1979)
* Haaren (0788) komt te vervallen, en wordt verdeeld tussen
Oisterwijk (0824), Vught (0865), Boxtel (0757), en Tilburg (0855).
Woonplaats Biezenmortel (1425) wordt bij gemeente Tilburg (0855) gevoegd.
Woonplaats Esch (1426) wordt bij gemeente Boxtel (0757) gevoegd.
Woonplaats Haaren (1427) wordt bij gemeente Oisterwijk (0824) gevoegd.
Woonplaats Helvoirt (1428) wordt bij gemeente Vught (0865) gevoegd.
Zie ook:
* [CBS - Gemeentelijke indeling op 1 januari 2021](https://www.cbs.nl/nl-nl/onze-diensten/methoden/classificaties/overig/gemeentelijke-indelingen-per-jaar/indeling-per-jaar/gemeentelijke-indeling-o …
=> Update gemeente-provincie koppeling voor 2021.

brk/etl/etl.sh
In alle etl.sh-scripts wordt gebruik gemaakt van pushd / popd om de paden correct over te nemen, zodat dit script ook aangeroepen kan worden vanuit andere mappen zonder fouten in verwijzingen. Bij de BRK ontbraken deze regels in dit script.
Deze PR voegt deze regels toe zodat ook de BRK etl.sh aangeroepen kan worden vanuit een andere map als waarin etl.sh staat.
=> Toevoeging push/popd aan BRK etl.sh

bag/bin/bag-extract.sh, bag/bin/gemeentelijke-indeling.sh
On Debian bullseye/sid there is no `python` by default any more, either the `python-is-python2` or `python-is-python3` package needs to be installed to provide `/usr/bin/python`.
When there is no `python` in `PATH` the version detection in `bag-extract.sh` & `gemeentelijke-indeling.sh` fail.
This PR fixes that by not assuming that `python` is available, it first tries to find that and ensure it's version 3, or it tries to find `python3`.
=> Fix python detection.

bagv2/etl/README.md
De LVBAG driver is toegevoegd in GDAL 3.2.0.
In GDAL 3.3.0 is het `identificatie` veld toegevoegd.
En in GDAL 3.4.0 zijn `woonplaatsRef` (voor `Nummeraanduiding` objecten)
en `verkorteNaam` (voor `OpenbareRuimte` objecten) toegevoegd.
Fixes: #330
=> BAGv2 Bump GDAL versie naar 3.4.0.

bagv2/README.md
The extracten.bag.kadaster.nl server is being phased out:
> **Vanaf 11 oktober worden er geen nieuwe BAG 2.0 Extracten gepubliceerd op deze server.**
Wilt u gebruik blijven maken van het BAG 2.0 Extract? Kijk dan op [de productpagina van het BAG 2.0 Extract](https://www.kadaster.nl/zakelijk/producten/adressen-en-gebouwen/bag-2.0-extract) voor de verschillende mogelijkheden.
> 
> Vanaf januari 2022 is de Externe server niet meer te benaderen. Hiermee stopt de mogelijkheid om de oude BAG 2.0 Extracten te downloaden.
Alternatively we could document: https://www.kadaster.nl/-/kosteloze-download-bag-2.0-extract
=> Add BAGv2 Atom feed

bag/db/data/gemeentelijke-indeling.xml
Per 1 januari 2022 word de nieuwe gemeentelijke indeling actief:
* Beemster (0370) komt te vervallen, en wordt bij de gemeente Purmerend (0439) gevoegd.
* Heerhugowaard (0398) & Langedijk (0416) komen te vervallen, en worden de nieuwe gemeente Dijk en Waard (1980).
* Landerd (1685) & Uden (0856) komen te vervallen, en worden de nieuwe gemeente Maashorst (1991).
* Boxmeer (0756), Cuijk (1684), Grave (0786), Mill en Sint Hubert (0815), en Sint Anthonis (1702) komen te vervallen, en worden de nieuwe gemeente Land van Cuijk (1982).
Zie ook:
* [CBS - Gemeentelijke indeling op 1 januari 2022](https://www.cbs.nl/nl-nl/onze-diensten/methoden/classificaties/overig/gemeentelijke-indelingen-per-jaar/indeling-per-jaar/gemeentelijke-indeling-op-1-januari-2022)
* [Wikipedia - Gemeentelijke …
=> Update gemeente-provincie koppeling voor 2022.

bag/db/data/gemeentelijke-indeling.xml
In 2002 is de gemeente Vianen van provincie gewijzigd (van Zuid-Holland naar Utrecht).
De indelingen van 2003 en later gebruikten echter de begindatum van de gemeente in provincie Zuid-Holland ipv Utrecht.
=> Correct begindatum for Vianen.

bagv2/etl/sql/create-indexes.sql, bagv2/etl/sql/create-views.sql
Om een bijzonder oud issue met de gemeentelijke indeling en actueelbestaand VIEWs op te lossen moet de stand datum gebruikt worden in plaats van NOW/LOCALTIMESTAMP.
Omdat de maandelijke extract van december in januari ook nog gebruikt kan worden, is het niet goed dat de gemeentelijke indeling van het nieuwe jaar vanaf januari gebruikt wordt. De nieuwe gemeentelijke indeling is in de maandelijkse extract van december immers nog niet verwerkt.
Wanneer #319 gemerged is kan de SQL voor de `provincie_gemeenteactueelbestaand` VIEW ook aangepast worden.
Zie ook:
* https://github.com/nlextract/NLExtract/pull/158#issuecomment-168345951
* #311
=> Gebruik BAG stand datum in plaats van NOW/LOCALTIMESTAMP.

bagv2/etl/sql/create-meta.sql, bagv2/etl/xsl/Leveringsdoc2gml.xsl
In plaats van de `bag_xsd_versie` waarde te hardcoden wordt de `SchemaInfo` uit `Leveringsdocument-BAG-Extract.xml` gebruikt.
Fixes: #333
=> Extract SchemaInfo from Leveringsdocument-BAG-Extract.xml.

bagv2/etl/sql/create-views.sql
WHERE-clauses in de `actueel` en `actueelbestaand` views zijn aangepast.
Het was: 
`eindDatumTijdvakGeldigheid >= extract_datum()` 
Het is nu:
`eindDatumTijdvakGeldigheid > extract_datum()`
De aangepaste clause zorgt ervoor dat objecten met `eindDatumTijdvakGeldigheid = extract_datum()` niet meer in de actueel(bestaand) views voorkomen.
Zelfde is toegepast op `einddatum` en`tijdstipinactief` in de view-definities voor de koppeltabellen.
Fixes #343.
=> Fix filter op einddatum in de views `actueel` en `actueelbestaand`

bagv2/etl/sql/create-views.sql
PR voor issue #341. Viewdefinities aangepast en ook de formattering van het SQL-script verbeterd. Beide zaken in een eigen commit.
=> Extract datum view

bag/db/data/gemeentelijke-indeling.xml, bagv2/etl/data/cbs/gemeentelijke-indeling.csv
Per 1 januari 2023 word de nieuwe gemeentelijke indeling actief:
* Brielle (0501), Hellevoetsluis (0530), en Westvoorne (0614) komen te vervallen, en worden de nieuwe gemeente Voorne aan Zee (1992).
Zie ook:
* [CBS - Gemeentelijke indeling op 1 januari 2023](https://www.cbs.nl/nl-nl/onze-diensten/methoden/classificaties/overig/gemeentelijke-indelingen-per-jaar/indeling-per-jaar/gemeentelijke-indeling-op-1-januari-2023)
* [Wikipedia - Gemeentelijke herindelingen in Nederland](https://nl.wikipedia.org/wiki/Gemeentelijke_herindelingen_in_Nederland#Herindeling_1_januari_2023)
=> Update gemeente-provincie koppeling voor 2023.

bag/db/data/gemeentelijke-indeling.xml
Er zijn geen wijzigingen ten opzichte van 2023.
Zie ook:
* [CBS - Gemeentelijke indeling op 1 januari 2024](https://www.cbs.nl/nl-nl/onze-diensten/methoden/classificaties/overig/gemeentelijke-indelingen-per-jaar/indeling-per-jaar/gemeentelijke-indeling-op-1-januari-2024)
=> Update gemeente-provincie koppeling voor 2024.

stetlcomponents/gfspreparationfilter.py
Small PR. When processing a small DKK dataset it appears that the old GFS file is being reused when OGRInfo is being executed. Therefor the name of the GFS file should be determined earlier, and if this file already exists, it should be removed.
=> Generate GFS name earlier and remove old file if it exists

bag/db/data/gemeentelijke-indeling.xml, bag/src/gemeentelijke-indeling.py, bagv2/etl/data/cbs/gemeentelijke-indeling.csv
Er zijn geen wijzigingen ten opzichte van 2024.
Wel zijn de namen van een aantal gemeenten aangepast.
Uit de toelichting:
> Voor de volgende gemeenten is in deze tabel achter de gemeentenaam nu ook de afkorting van de provincie vermeld.
>
> Beek (L.)
> Hengelo (O.)
> Laren (NH.)
> Middelburg (Z.)
> Rijswijk (ZH.)
> Stein (L.)
>
> Vanaf 2024 wordt in tabellen met gemeentenamen aan deze 6 gemeenten de afkorting van de provincie aan de naam toegevoegd. CBS streeft ernaar in alle tabellen dezelfde gemeentenamen te hanteren.  De genoemde gemeenten kwamen in het verleden in meerdere provincies voor. Deze gemeenten hebben in tabellen met tijdreeksen of oudere tabellen daarom de afkorting van de provincie achter hun naam. Dezelfde namen worden nu ook in de tabellen vanaf 2024 vermeld.
> Voor de …
=> Update gemeente-provincie koppeling voor 2025.

bagv2/etl/sql/adres/adres-tabel-plus.sql
Toevoegen van order by in de crosstab functie omdat anders vbo_id niet uniek wordt en het maken van de PK fout loopt
=> add orderin adres_plus crosstab function

bag/README.md, bag/src/bagdownloadgui.py, doc/source/algemeen.rst, doc/source/bagextract.rst
Ik las de documentatie en kwam dead-links tegen, de open data distributie is nogal veranderlijk. Zie https://geoforum.nl/t/oude-url-s-inspire-adressen-uitgefaseerd/7325/1
Misschien ook een idee om de hele `bag` (v1)-directory op te ruimen, net als `ddkv3`. Want die bestanden/urls zijn er niet meer.
=> Fix documentation / dead links
